name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send webhook to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "username": "GitHub Update",
          "embeds": [{
            "title": "Client Config Files Update",
            "description": "New updates are available for the Client Config Files.",
            "color": 5814783,
            "fields": [
              {
                "name": "Download Config Files Here",
                "value": "[Download Files](https://github.com/BirdieTX/Queens-Guard-FIKA-Server/archive/master.zip)"
              },
              {
                "name": "Read More About Installation Instructions",
                "value": "[Read More](https://github.com/BirdieTX/Queens-Guard-FIKA-Server/blob/main/README.md)"
              },
              {
                "name": "Installation Guide Channel",
                "value": "For more detailed guidance, please check the #install-guide channel."
              }
            ],
            "footer": {
              "text": "GitHub to Discord Integration"
            }
          }]
        }' \
        $DISCORD_WEBHOOK_URL
